command: ["uvicorn", "src.custom_server.app:app", "--host", "0.0.0.0", "--port", "8000"]

# Environment variables for the app
env:
  - name: DATABRICKS_HOST
    value: "https://adb-1761712055023179.19.azuredatabricks.net"
  - name: DATABRICKS_WAREHOUSE_ID
    value: "a85c850e7621e163"
  - name: LOG_LEVEL
    value: "DEBUG"

# Enable authentication
permissions:
  - type: "user_access_token"
    level: "CAN_USE"
