name: databricks-mcp-server

command: ["uvicorn", "src.custom_server.app:app", "--host", "0.0.0.0", "--port", "8000", "--log-level", "debug"]
# Environment variables for the app
env:
  - name: DATABRICKS_HOST
    value: "https://adb-1761712055023179.19.azuredatabricks.net"
  - name: DATABRICKS_WAREHOUSE_ID
    value: "6af12ef900c45a85"
  - name: LOG_LEVEL
    value: "DEBUG"
  - name: FORWARDED_ALLOW_IPS
    value: "*"
  - name: PROXY_HEADERS_TRUSTED
    value: "true"

# Enable authentication
permissions:
  - type: "user_access_token"
    level: "CAN_USE"
